RANDOM_STATE = 5
VERBOSE = True
NUM_WORKERS = 8
SAVE_PATH = '../output'

IMG_SIZE = 64
BATCH_SIZE = 32
IMAGE_CHANNELS = 3
DATA_DIR = "../data/star-wars-images/"

TIMESTEPS = 200
BETA_START = 1e-4
BETA_END = 2e-2

NUM_MODULE_LAYERS = 5
NUM_TIME_EMBEDDINGS = 32
KERNEL_SIZE = 3
LEARNING_RATE = 1e-3
NUM_EPOCHS = 5
LIMIT_VAL_BATCHES_RATIO = 0.05